### ISSUE TITLE
Fix up the Resources page on neurobridges.org

### ISSUE THREAD

**Issue by HowardLander** [NeuroBridge/NeuroBridge1.0#27]
There are a couple of issues: 

- When you select Resources from the main page, you end up at the right place, but the URL is https://neurobridges.org/software instead of https://neurobridges.org/resources
- On the Resources page itself, we like to add a link to the latest ontology.  That ontology is at https://github.com/NeuroBridge/neuro-ontologies/blob/main/neurobridge/NeuroBridge_032423.owl.  I think we should add another section like the existing GitHub section, only it should say Ontology in the left panel.  I think the text can just say something like "Click below to directly access the current ontology"

**Comment by mbwatson** [comment]
@HowardLander does everything look good?

https://neurobridges.org/

**Comment by HowardLander** [comment]
I think so
________________________________
